[package]
name = "urlmatic"
version = "0.1.0"
edition = "2021"
description = "Generate a series of timestamps between two bounds."
repository = "https://github.com/bww/urlmatic"
readme = "README.md"
license = "BSD-3-Clause"

[dependencies]
url = "2.2.2"
structopt = "0.3"
