[package]
name = "urlmatic"
version = "0.2.1"
edition = "2021"
description = "Slice and dice URLs on the command line"
repository = "https://github.com/bww/urlmatic"
readme = "README.md"
license = "BSD-3-Clause"

[dependencies]
url = "2.2.2"
clap = { version="3.1", features=["derive"] }
